# Generated by Django 3.2 on 2022-02-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='delo',
            field=models.CharField(max_length=60),
        ),
    ]
