# Generated by Django 3.2 on 2022-02-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_todolist_delo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='delo',
            field=models.TextField(),
        ),
    ]
